import type { ConnectorDefinition } from './types'

export const CONNECTORS: ConnectorDefinition[] = [
  {
    slug: 'silae',
    name: 'My Silae',
    description: 'Importez les congés validés. Les créneaux sont bloqués automatiquement dans le calendrier.',
    category: 'rh',
    logoColor: '#1A3A6B',
    logoInitials: 'Si',
    authType: 'api_key',
    features: ['Congés auto-bloqués', 'Absences', 'Sync webhook'],
    setupMinutes: 2,
    plan: 'business',
  },
  {
    slug: 'pennylane',
    name: 'Pennylane',
    description: 'Une facture est créée automatiquement dans Pennylane à chaque rendez-vous terminé.',
    category: 'comptabilite',
    logoColor: '#5B21B6',
    logoInitials: 'PL',
    authType: 'oauth',
    features: ['Factures auto', 'Sync clients', 'Export CA'],
    setupMinutes: 2,
    plan: 'business',
  },
  {
    slug: 'odoo',
    name: 'Odoo',
    description: 'Synchronisez vos RDV avec votre ERP Odoo. Facturation, clients, stock produits.',
    category: 'comptabilite',
    logoColor: '#714B67',
    logoInitials: 'Od',
    authType: 'api_key',
    features: ['Factures', 'CRM', 'Stock'],
    setupMinutes: 5,
    plan: 'business',
  },
  {
    slug: 'google-calendar',
    name: 'Google Calendar',
    description: 'Synchronisation bidirectionnelle. Les RDV apparaissent dans l\'agenda Google de chaque employé.',
    category: 'agenda',
    logoColor: '#4285F4',
    logoInitials: 'G',
    authType: 'oauth',
    features: ['Sync bidirectionnelle', 'Par employé', 'Temps réel'],
    setupMinutes: 2,
    plan: 'pro',
  },
  {
    slug: 'whatsapp',
    name: 'WhatsApp Business',
    description: 'Envoyez les rappels et confirmations de RDV via WhatsApp. Taux d\'ouverture > 90%.',
    category: 'communication',
    logoColor: '#25D366',
    logoInitials: 'Wa',
    authType: 'api_key',
    features: ['Rappels RDV', 'Confirmations', 'Annulations'],
    setupMinutes: 5,
    plan: 'pro',
  },
  {
    slug: 'factorial',
    name: 'Factorial HR',
    description: 'Importez absences et congés validés directement dans le calendrier KalendHair.',
    category: 'rh',
    logoColor: '#FF6B35',
    logoInitials: 'Fa',
    authType: 'oauth',
    features: ['Congés', 'Planning équipe', 'Webhook'],
    setupMinutes: 2,
    plan: 'business',
  },
]

export function getConnector(slug: string): ConnectorDefinition | undefined {
  return CONNECTORS.find(c => c.slug === slug)
}
